/**
 * Declared-limit and excluded-page behaviour (spec §10).
 *
 * Both fixtures are generated by `npm run fixtures:sample`. Neither reaches the network: an
 * over-limit document must not issue a search at all.
 */
import { expect, test } from "@playwright/test";
import type { Page } from "@playwright/test";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const BLANK_PAGE = resolve(here, "fixtures/sample-blank-page-ja.pdf");
const OVER_LIMIT = resolve(here, "fixtures/sample-over-limit-ja.pdf");
const ENCRYPTED = resolve(here, "fixtures/sample-encrypted.pdf");
const NO_TEXT = resolve(here, "fixtures/sample-no-text.pdf");
const ALL = [BLANK_PAGE, OVER_LIMIT, ENCRYPTED, NO_TEXT];

test("the limit fixtures are present", () => {
    const missing = ALL.filter((path) => !existsSync(path));
    expect(missing, `Run \`npm run fixtures:sample\`. Missing: ${missing.join(", ")}`).toEqual([]);
});

test.describe("declared limits", () => {
    test.skip(() => ALL.some((path) => !existsSync(path)), "limit fixtures not present");

    const open = async (page: Page, fixture: string) => {
        await page.goto("/");
        await page.setInputFiles('input[type="file"]', fixture);
        await page.waitForSelector(".pdf-finder-page");
    };

    test("names the pages that produced no text and keeps searching the rest", async ({ page }) => {
        await open(page, BLANK_PAGE);
        await page.waitForFunction(() => document.querySelectorAll(".textLayer span").length > 5);

        await expect(page.locator("footer p")).toContainText("no text on page 2");
        await expect(page.locator("footer p")).toContainText("3 pages");

        // The pages that do have text remain searchable.
        await page.locator('label:has-text("Exact text")').click();
        await page.getByLabel("Search query").fill("返還は行わない");
        await page.getByLabel("Search query").press("Enter");
        await expect(page.locator("ol li")).toHaveCount(1);
    });

    test("says which pages could not be searched when nothing was found", async ({ page }) => {
        await page.route("**/api/search", async (route) => {
            const body = JSON.parse(route.request().postData() ?? "{}") as { documentId: string; requestId: string };
            await route.fulfill({
                json: {
                    documentId: body.documentId,
                    requestId: body.requestId,
                    status: "no_match",
                    results: [],
                    evaluatedSegmentCount: 2,
                    model: "jev-1.13.0",
                    elapsedMs: 10,
                },
            });
        });

        await open(page, BLANK_PAGE);
        await page.waitForFunction(() => document.querySelectorAll(".textLayer span").length > 5);

        await page.locator('label:has-text("Meaning")').click();
        await page.getByLabel("Search query").fill("ログインの方法は");
        await page.getByRole("button", { name: "Search" }).click();

        // The scope of the search and its result are two separate statements: an empty result over
        // part of a document must not read as "the document does not say".
        await expect(page.getByText("Page 2 could not be searched")).toBeVisible();
        await expect(page.getByText("in the text that could be searched")).toBeVisible();
    });

    test("blocks search on an over-limit document without truncating or requesting anything", async ({ page }) => {
        let requested = false;
        await page.route("**/api/search", async (route) => {
            requested = true;
            await route.abort();
        });

        await open(page, OVER_LIMIT);
        await page.waitForFunction(() => document.querySelectorAll(".textLayer span").length > 50);

        // The document is still rendered and readable; only search is withheld.
        await expect(page.locator(".pdf-finder-page")).toHaveCount(9);
        await expect(page.getByRole("button", { name: "View extracted text" })).toBeVisible();

        // The limit is named with real numbers rather than a generic refusal.
        const message = page.locator("form p.text-error-primary");
        await expect(message).toContainText("The limit is 50,000");
        await expect(message).toContainText("Search is unavailable for this document");

        await expect(page.getByLabel("Search query")).toBeDisabled();
        await expect(page.getByRole("button", { name: "Search" })).toBeDisabled();

        await page
            .getByRole("button", { name: "Search" })
            .click({ force: true })
            .catch(() => undefined);
        await page.waitForTimeout(800);
        expect(requested).toBe(false);
    });

    test("stops loading a password-protected document and gives the reason", async ({ page }) => {
        await page.goto("/");
        await page.setInputFiles('input[type="file"]', ENCRYPTED);

        await expect(page.getByText("password protected")).toBeVisible();
        await expect(page.locator(".pdf-finder-page")).toHaveCount(0);
        await expect(page.getByRole("button", { name: "Search" })).toBeDisabled();
    });

    test("explains that a document with no extractable text needs a text-based PDF", async ({ page }) => {
        await page.goto("/");
        await page.setInputFiles('input[type="file"]', NO_TEXT);

        // Spec §10 is explicit that OCR is not a fallback, so the message says so.
        await expect(page.getByText("requires a text-based PDF")).toBeVisible();
        await expect(page.getByText("does not run OCR")).toBeVisible();
    });

    test("issues no request while the reader is typing, or while moving between results", async ({ page }) => {
        let requests = 0;
        await page.route("**/api/search", async (route) => {
            requests += 1;
            const body = JSON.parse(route.request().postData() ?? "{}") as {
                documentId: string;
                requestId: string;
                segments: Array<{ id: string }>;
            };
            await route.fulfill({
                json: {
                    documentId: body.documentId,
                    requestId: body.requestId,
                    status: "matched",
                    results: body.segments.slice(0, 3).map((segment, index) => ({
                        segmentId: segment.id,
                        score: 2 - index * 0.1,
                        relevantProbability: 0.95 - index * 0.05,
                        confidence: 0.9,
                    })),
                    evaluatedSegmentCount: body.segments.length,
                    model: "jev-1.13.0",
                    elapsedMs: 1,
                },
            });
        });

        await open(page, BLANK_PAGE);
        await page.waitForFunction(() => document.querySelectorAll(".textLayer span").length > 5);
        await page.locator('label:has-text("Meaning")').click();

        await page.getByLabel("Search query").type("解約したらお金は戻りますか", { delay: 30 });
        await page.waitForTimeout(1200);
        expect(requests).toBe(0);

        await page.getByRole("button", { name: "Search" }).click();
        await expect(page.locator("ol li")).not.toHaveCount(0);
        expect(requests).toBe(1);

        // Spec §3: moving through existing results never queries again.
        for (let step = 0; step < 4; step += 1) {
            await page
                .getByRole("button", { name: step % 2 === 0 ? "Next" : "Previous" })
                .click()
                .catch(() => undefined);
        }
        await page.waitForTimeout(800);
        expect(requests).toBe(1);
    });
});
