/**
 * Declared-limit and excluded-page behaviour (spec §10).
 *
 * Both fixtures are generated by `npm run fixtures:sample`. Neither reaches the network: an
 * over-limit document must not issue a search at all.
 */
import { expect, test } from "@playwright/test";
import type { Page } from "@playwright/test";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { LIMITS } from "@/lib/types";
import { stubChallenge } from "./stub-challenge";

const here = dirname(fileURLToPath(import.meta.url));
const BLANK_PAGE = resolve(here, "fixtures/sample-blank-page-ja.pdf");
const OVER_LIMIT = resolve(here, "fixtures/sample-over-limit-ja.pdf");
const ENCRYPTED = resolve(here, "fixtures/sample-encrypted.pdf");
const NO_TEXT = resolve(here, "fixtures/sample-no-text.pdf");
const TWO_COLUMN = resolve(here, "fixtures/sample-two-column-ja.pdf");
const TOO_MANY_PAGES = resolve(here, "fixtures/sample-too-many-pages-ja.pdf");
const DENSE = resolve(here, "fixtures/sample-dense-ja.pdf");
const NEAR_LIMIT = resolve(here, "fixtures/sample-near-limit-ja.pdf");
const ALL = [BLANK_PAGE, OVER_LIMIT, ENCRYPTED, NO_TEXT, TWO_COLUMN, TOO_MANY_PAGES, DENSE, NEAR_LIMIT];

test("the limit fixtures are present", () => {
    const missing = ALL.filter((path) => !existsSync(path));
    expect(missing, `Run \`npm run fixtures:sample\`. Missing: ${missing.join(", ")}`).toEqual([]);
});

test.beforeEach(async ({ page }) => {
    await stubChallenge(page);
});

test.describe("declared limits", () => {
    test.skip(() => ALL.some((path) => !existsSync(path)), "limit fixtures not present");

    const open = async (page: Page, fixture: string) => {
        await page.goto("/");
        await page.setInputFiles('input[type="file"]', fixture);
        await page.waitForSelector(".pdf-finder-page");
    };

    test("names the pages that produced no text and keeps searching the rest", async ({ page }) => {
        await open(page, BLANK_PAGE);
        await page.waitForFunction(() => document.querySelectorAll(".textLayer span").length > 5);

        await expect(page.locator("footer p")).toContainText("no text on page 2");
        // The document's identity lives in the header now; the footer carries only the timings.
        await expect(page.locator("header p")).toContainText("3 pages");

        // The pages that do have text remain searchable.
        await page.getByRole("radio", { name: "Exact text" }).click();
        await page.getByLabel("Search query").fill("返還は行わない");
        await page.getByLabel("Search query").press("Enter");
        await expect(page.locator("ol li")).toHaveCount(1);
    });

    test("says which pages could not be searched when nothing was found", async ({ page }) => {
        await page.route("**/api/search", async (route) => {
            const body = JSON.parse(route.request().postData() ?? "{}") as { documentId: string; requestId: string; segments: { id: string }[] };
            await route.fulfill({
                contentType: "application/x-ndjson",
                body:
                    JSON.stringify({
                        type: "final",
                        documentId: body.documentId,
                        requestId: body.requestId,
                        status: "no_match",
                        results: [],
                        evaluatedSegmentCount: body.segments.length,
                        requestCount: 1,
                        model: "jev-1.13.0",
                        elapsedMs: 10,
                    }) + "\n",
            });
        });

        await open(page, BLANK_PAGE);
        await page.waitForFunction(() => document.querySelectorAll(".textLayer span").length > 5);

        await page.getByRole("radio", { name: "Meaning" }).click();
        await page.getByLabel("Search query").fill("ログインの方法は");
        await page.getByRole("button", { name: "Search", exact: true }).click();

        // The scope of the search and its result are two separate statements: an empty result over
        // part of a document must not read as "the document does not say".
        await expect(page.getByText("Page 2 could not be searched")).toBeVisible();
        // A meaning search that finds nothing has made a judgement against a threshold; it has not
        // established that the document says nothing. The wording says which of the two happened.
        await expect(page.getByText("No passage in the text that could be searched met the relevance threshold")).toBeVisible();
        // And the limit that holds on every page, not just the excluded ones: a page whose body is
        // an image yields some text, so nothing above would mention it.
        await expect(page.getByText("Text inside images was not searched")).toBeVisible();
    });

    test("blocks search on an over-limit document without truncating or requesting anything", async ({ page }) => {
        let requested = false;
        await page.route("**/api/search", async (route) => {
            requested = true;
            await route.abort();
        });

        await open(page, OVER_LIMIT);
        await page.waitForFunction(() => document.querySelectorAll(".textLayer span").length > 50);

        // The document is still rendered and readable; only search is withheld.
        await expect(page.locator(".pdf-finder-page")).toHaveCount(41);
        await expect(page.getByRole("button", { name: "View extracted text" })).toBeVisible();

        // The limit is named with real numbers rather than a generic refusal, and the number comes
        // from the code so raising the limit cannot leave this assertion quietly describing the
        // old one.
        const message = page.locator("form p.text-error-primary");
        await expect(message).toContainText(`The limit is ${LIMITS.maxExtractedCharacters.toLocaleString("en-US")}`);
        await expect(message).toContainText("Search is unavailable for this document");

        await expect(page.getByLabel("Search query")).toBeDisabled();
        await expect(page.getByRole("button", { name: "Search", exact: true })).toBeDisabled();

        await page
            .getByRole("button", { name: "Search", exact: true })
            .click({ force: true })
            .catch(() => undefined);
        await page.waitForTimeout(800);
        expect(requested).toBe(false);
    });

    test("refuses a document over the page limit, and renders none of it", async ({ page }) => {
        // The page-count path had no fixture at all until now: every existing one is inside the
        // page limit and over some other one. This document is 1,000 pages.
        await page.goto("/");
        await page.setInputFiles('input[type="file"]', TOO_MANY_PAGES);

        const message = page.locator("p.text-error-primary");
        await expect(message).toContainText(`The limit is ${LIMITS.maxPageCount}`);
        await expect(message).toContainText("1000 pages");

        // Not "rendered but unsearchable", as an over-character document is: nothing is opened,
        // so the drop zone is still the only thing on screen.
        await expect(page.locator(".pdf-finder-page")).toHaveCount(0);
        await expect(page.locator("[data-dropzone]")).toBeVisible();
        await expect(page.getByLabel("Search query")).toBeDisabled();
    });

    test("stops reading a document that carries more text than the extraction ceiling", async ({ page }) => {
        // Inside the page limit — 48 pages — and over a million characters, because a page limit
        // says nothing about how much text one page may hold. Extraction stops partway, and the
        // reader is told that what they can see is incomplete rather than being shown a partial
        // extraction as though it were the document.
        await page.goto("/");
        await page.setInputFiles('input[type="file"]', DENSE);
        await page.waitForSelector(".pdf-finder-page");

        const message = page.locator("form p.text-error-primary");
        await expect(message).toContainText("Extraction stopped at page");
        await expect(message).toContainText("the extracted text is incomplete");
        await expect(message).toContainText("Search is unavailable");

        // Rendered and readable, like every other over-limit document (spec §10).
        await expect(page.locator(".pdf-finder-page").first()).toBeVisible();
        await expect(page.getByLabel("Search query")).toBeDisabled();
    });

    test("reports every occurrence while mounting only a window of them", async ({ page }) => {
        // Exact search returns every occurrence and §6.1 forbids capping that. Rendering every
        // occurrence is a different promise: measured on this fixture, a one-word query produced
        // 3,744 results, took a second to paint, and left the search box needing 1.6 seconds to
        // accept four typed characters.
        await open(page, NEAR_LIMIT);
        await page.getByRole("radio", { name: "Exact text", exact: true }).click();
        await page.getByLabel("Search query").fill("協議");
        await page.getByRole("button", { name: "Search", exact: true }).click();

        await expect(page.locator("ol li").first()).toBeVisible();

        // The count is of the document, not of the list.
        const reported = Number(/([\d,]+) results/u.exec(await page.locator("aside p").first().innerText())![1].replaceAll(",", ""));
        expect(reported).toBeGreaterThan(1_000);
        expect(await page.locator("ol li").count()).toBeLessThan(reported / 10);

        // And the reader is told what is not mounted yet, rather than the list simply ending.
        await expect(page.getByText(/more — scroll to load/u)).toBeVisible();

        // Typing stays responsive, which is the whole point.
        const startedAt = Date.now();
        await page.getByLabel("Search query").fill("協議する");
        expect(Date.now() - startedAt).toBeLessThan(800);
    });

    test("keeps every occurrence reachable past the end of the window", async ({ page }) => {
        await open(page, NEAR_LIMIT);
        await page.getByRole("radio", { name: "Exact text", exact: true }).click();
        await page.getByLabel("Search query").fill("協議");
        await page.getByRole("button", { name: "Search", exact: true }).click();
        await expect(page.locator("ol li").first()).toBeVisible();

        const mounted = await page.locator("ol li > button").count();
        expect(mounted).toBeGreaterThan(10);

        // Walk past the end of what is mounted. Next moves through the whole list, so the window
        // has to follow it rather than the other way round.
        const next = page.getByRole("button", { name: "Next" });
        for (let step = 0; step < mounted + 5; step += 1) await next.click();

        await expect(page.locator("ol li > button[aria-current='true']")).toHaveCount(1);
        expect(await page.locator("ol li > button").count()).toBeGreaterThan(mounted);
        await expect(page.locator(".pdf-finder-highlight").first()).toBeVisible();
    });

    test("stops loading a password-protected document and gives the reason", async ({ page }) => {
        await page.goto("/");
        await page.setInputFiles('input[type="file"]', ENCRYPTED);

        await expect(page.getByText("password protected")).toBeVisible();
        await expect(page.locator(".pdf-finder-page")).toHaveCount(0);
        await expect(page.getByRole("button", { name: "Search", exact: true })).toBeDisabled();
    });

    test("explains that a document with no extractable text needs a text-based PDF", async ({ page }) => {
        await page.goto("/");
        await page.setInputFiles('input[type="file"]', NO_TEXT);

        // Spec §10 is explicit that OCR is not a fallback, so the message says so.
        await expect(page.getByText("requires a text-based PDF")).toBeVisible();
        await expect(page.getByText("does not run OCR")).toBeVisible();
    });

    test("names a page whose layout it does not claim to handle", async ({ page }) => {
        await open(page, TWO_COLUMN);
        await page.waitForFunction(() => document.querySelectorAll(".textLayer span").length > 5);

        // Extraction splits at the gutter so the columns do not fuse, but the order between them
        // is still row by row. A comment claiming the page is reported is not the page being
        // reported: it has to reach the reader.
        await expect(page.locator("footer p")).toContainText("side-by-side text on page 1");
    });

    test("reads a two-column page down one column and then the next", async ({ page }) => {
        // Reading across the gutter does not merely reorder the text, it interleaves it: the left
        // column's sentence is cut and the right column's inserted into it. Every passage built
        // from that is nonsense, so this checks the extracted text, not just the warning.
        await open(page, TWO_COLUMN);
        await page.waitForFunction(() => document.querySelectorAll(".textLayer span").length > 20);

        await page.getByRole("button", { name: "View extracted text" }).click();
        const texts = await page.locator("article > p").evaluateAll((nodes) => nodes.map((node) => node.textContent ?? ""));

        expect(texts.length).toBeGreaterThan(1);
        const fused = texts.filter((text) => text.includes("左第") && text.includes("右第"));
        expect(fused, "a passage carries both columns").toEqual([]);

        // And the order is column by column: every left-column passage precedes every right one.
        const lastLeft = texts.findLastIndex((text) => text.includes("左第"));
        const firstRight = texts.findIndex((text) => text.includes("右第"));
        expect(firstRight).toBeGreaterThan(lastLeft);
    });

    test("says the layout was not fully understood when a search finds nothing", async ({ page }) => {
        await page.route("**/api/search", async (route) => {
            const body = JSON.parse(route.request().postData() ?? "{}") as { documentId: string; requestId: string; segments: { id: string }[] };
            await route.fulfill({
                contentType: "application/x-ndjson",
                body:
                    JSON.stringify({
                        type: "final",
                        documentId: body.documentId,
                        requestId: body.requestId,
                        status: "no_match",
                        results: [],
                        evaluatedSegmentCount: body.segments.length,
                        requestCount: 1,
                        model: "jev-1.13.0",
                        elapsedMs: 10,
                    }) + "\n",
            });
        });

        await open(page, TWO_COLUMN);
        await page.waitForFunction(() => document.querySelectorAll(".textLayer span").length > 5);

        await page.getByRole("radio", { name: "Meaning" }).click();
        await page.getByLabel("Search query").fill("ログインの方法は");
        await page.getByRole("button", { name: "Search", exact: true }).click();

        // Separate from "could not be searched": these pages were searched, just not understood.
        await expect(page.getByText("does not fully support")).toBeVisible();
        await expect(page.getByText("could not be searched")).toHaveCount(0);
    });

    test("issues no request while the reader is typing, or while moving between results", async ({ page }) => {
        let requests = 0;
        await page.route("**/api/search", async (route) => {
            requests += 1;
            const body = JSON.parse(route.request().postData() ?? "{}") as {
                documentId: string;
                requestId: string;
                segments: Array<{ id: string }>;
            };
            await route.fulfill({
                contentType: "application/x-ndjson",
                body:
                    JSON.stringify({
                        type: "final",
                        documentId: body.documentId,
                        requestId: body.requestId,
                        status: "matched",
                        results: body.segments.slice(0, 3).map((segment, index) => ({
                            segmentId: segment.id,
                            score: 2 - index * 0.1,
                            relevantProbability: 0.95 - index * 0.05,
                            confidence: 0.9,
                        })),
                        evaluatedSegmentCount: body.segments.length,
                        requestCount: 1,
                        model: "jev-1.13.0",
                        elapsedMs: 1,
                    }) + "\n",
            });
        });

        await open(page, BLANK_PAGE);
        await page.waitForFunction(() => document.querySelectorAll(".textLayer span").length > 5);
        await page.getByRole("radio", { name: "Meaning" }).click();

        await page.getByLabel("Search query").type("解約したらお金は戻りますか", { delay: 30 });
        await page.waitForTimeout(1200);
        expect(requests).toBe(0);

        await page.getByRole("button", { name: "Search", exact: true }).click();
        await expect(page.locator("ol li")).not.toHaveCount(0);
        expect(requests).toBe(1);

        // Spec §3: moving through existing results never queries again.
        for (let step = 0; step < 4; step += 1) {
            await page
                .getByRole("button", { name: step % 2 === 0 ? "Next" : "Previous" })
                .click()
                .catch(() => undefined);
        }
        await page.waitForTimeout(800);
        expect(requests).toBe(1);
    });
});
