/**
 * Viewer and search behaviour in a real browser (spec §11.2).
 *
 * `/api/search` is intercepted throughout, so every functional requirement here is exercised
 * without a TypeSafe credential. That also makes the concurrency requirements testable, since a
 * response can be delayed deliberately.
 *
 * These tests need a fixture PDF. See `tests/fixtures/README.md`.
 */
import { expect, test } from "@playwright/test";
import type { Page, Route } from "@playwright/test";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));

/**
 * The document these tests drive.
 *
 * `sample-contract-ja.pdf` is generated by `npm run fixtures:sample` and is a development aid, not
 * one of the acceptance fixtures in `tests/fixtures/README.md`. It carries the three properties
 * these tests need: a clause that answers a refund question without using the word the reader
 * would type, a sentence repeated on two different pages, and enough pages that zooming during a
 * load is reproducible. An acceptance fixture is preferred when one is present.
 */
const FIXTURE =
    process.env.PDF_FINDER_FIXTURE ??
    [resolve(here, "fixtures/contract-ja.pdf"), resolve(here, "fixtures/sample-contract-ja.pdf")].find((path) => existsSync(path)) ??
    resolve(here, "fixtures/sample-contract-ja.pdf");

/**
 * Always runs, and fails loudly when the fixtures are missing.
 *
 * Without it the whole suite would go green while testing nothing, which is exactly the
 * mock-only-success trap this repository's instructions warn about.
 */
test("fixture PDFs are present", () => {
    expect(existsSync(FIXTURE), `Fixture PDF missing: ${FIXTURE}. See tests/fixtures/README.md. Every other test in this file is skipped.`).toBe(true);
});

test.describe("appearance", () => {
    // Spec §3 asks for a quiet, light design. The starter this project grew from followed the
    // system preference, so a reader on a dark desktop saw a dark application.
    test("looks the same whether the system prefers light or dark", async ({ browser }) => {
        const sample = async (colorScheme: "light" | "dark") => {
            const context = await browser.newContext({ colorScheme });
            const page = await context.newPage();
            await page.goto("/");
            await page.waitForSelector("h1");

            const result = await page.evaluate(() => {
                const style = getComputedStyle(document.documentElement);
                return {
                    darkClass: document.documentElement.classList.contains("dark-mode"),
                    colorScheme: style.colorScheme,
                    body: getComputedStyle(document.body).backgroundColor,
                    heading: getComputedStyle(document.querySelector("h1")!).color,
                    // The drop zone is the only control on an empty page; the header's Open PDF
                    // button appears only once a document is loaded.
                    dropZone: getComputedStyle(document.querySelector("[data-dropzone]")!).backgroundColor,
                };
            });

            await context.close();
            return result;
        };

        const light = await sample("light");
        const dark = await sample("dark");

        // Nothing about the page may depend on the preference.
        expect(dark).toEqual(light);
        expect(dark.darkClass).toBe(false);
        // Pinned so native controls such as scrollbars cannot follow the dark preference either.
        expect(dark.colorScheme).toBe("light");
        expect(dark.body).toBe("rgb(255, 255, 255)");
    });
});

test.describe("viewer", () => {
    test.skip(() => !existsSync(FIXTURE), "fixture PDF not present");

    const openFixture = async (page: Page) => {
        await page.goto("/");
        await page.setInputFiles('input[type="file"]', FIXTURE);
        await page.waitForSelector(".pdf-finder-page");
        await page.waitForFunction(() => document.querySelectorAll(".textLayer span").length > 10);
    };

    const searchExact = async (page: Page, query: string) => {
        await page.getByRole("radio", { name: "Exact text" }).click();
        await page.getByLabel("Search query").fill(query);
        await page.getByRole("button", { name: "Search", exact: true }).click();
    };

    const searchMeaning = async (page: Page, query: string) => {
        await page.getByRole("radio", { name: "Meaning" }).click();
        await page.getByLabel("Search query").fill(query);
        await page.getByRole("button", { name: "Search", exact: true }).click();
    };

    /** Steps the zoom ladder until the label reads the requested level. */
    const setZoom = async (page: Page, target: string) => {
        for (let attempt = 0; attempt < 12; attempt += 1) {
            const current = (await page.getByLabel("Zoom level").textContent()) ?? "";
            if (current === target) return;
            const direction = Number(current.replace("%", "")) > Number(target.replace("%", "")) ? "Zoom out" : "Zoom in";
            await page.getByRole("button", { name: direction }).click();
        }
        throw new Error(`zoom never reached ${target}`);
    };

    const highlightText = (page: Page) => page.locator(".pdf-finder-highlight").evaluateAll((nodes) => nodes.map((node) => node.textContent).join(""));

    /**
     * Highlight position as a fraction of its page box, so it is comparable across zoom levels.
     *
     * Read from the document rather than through a resolved element handle. An exact-search
     * highlight is a span *inside* a text-layer element, and the effect that applies it tears the
     * span down and rebuilds it whenever the layer re-renders — so a handle resolved a moment
     * earlier can already be detached, and `closest()` returns null. Polling until a whole reading
     * succeeds measures the highlight that is actually on screen.
     *
     * Both rectangles are read inside one evaluation: fetching them in separate round-trips lets a
     * smooth scroll move one of them in between, which shows up as alignment drift that is not
     * there.
     */
    const highlightPosition = async (page: Page) => {
        const read = () =>
            page.evaluate(() => {
                const node = document.querySelector(".pdf-finder-highlight");
                const pageElement = node?.closest(".pdf-finder-page");
                if (node == null || pageElement == null) return null;

                const pageBox = pageElement.getBoundingClientRect();
                const box = node.getBoundingClientRect();
                if (pageBox.width === 0) return null;

                return {
                    left: (box.left - pageBox.left) / pageBox.width,
                    top: (box.top - pageBox.top) / pageBox.height,
                    pageWidth: pageBox.width,
                };
            });

        for (let attempt = 0; attempt < 30; attempt += 1) {
            const measured = await read();
            if (measured !== null) return measured;
            await page.waitForTimeout(100);
        }

        throw new Error("no highlight was on screen to measure");
    };

    const respondWith =
        (results: string[], status = "matched") =>
        async (route: Route) => {
            const body = JSON.parse(route.request().postData() ?? "{}") as { documentId: string; requestId: string; segments: { id: string }[] };
            await route.fulfill({
                contentType: "application/x-ndjson",
                body:
                    JSON.stringify({
                        type: "final",
                        documentId: body.documentId,
                        requestId: body.requestId,
                        status,
                        results: results.map((segmentId, index) => ({
                            segmentId,
                            score: 1.9 - index * 0.1,
                            relevantProbability: 0.95 - index * 0.05,
                            confidence: 0.8,
                        })),
                        evaluatedSegmentCount: body.segments.length,
                        requestCount: 3,
                        model: "jev-1.13.0",
                        elapsedMs: 120,
                    }) + "\n",
            });
        };

    const firstSegmentIds = async (page: Page, count: number): Promise<string[]> => {
        await page.getByRole("button", { name: "View extracted text" }).click();
        const ids = await page.locator("article header").evaluateAll((nodes) => nodes.map((node) => node.textContent?.match(/p\d{3}-s\d{3}/u)?.[0] ?? ""));
        await page.getByRole("button", { name: "Hide extracted text" }).click();
        return ids.filter((id) => id !== "").slice(0, count);
    };

    test("renders the document and reports what it extracted", async ({ page }) => {
        await openFixture(page);

        await expect(page.locator(".pdf-finder-page")).not.toHaveCount(0);
        await expect(page.locator("footer p")).toContainText("searchable segments");
    });

    test("exact mode makes no request to the semantic-search endpoint", async ({ page }) => {
        let called = false;
        await page.route("**/api/search", async (route) => {
            called = true;
            await route.abort();
        });

        await openFixture(page);
        await searchExact(page, "解約");
        await page.waitForTimeout(1000);

        expect(called).toBe(false);
    });

    test("selecting a result navigates to its physical page", async ({ page }) => {
        await openFixture(page);
        const ids = await firstSegmentIds(page, 3);
        const target = ids.at(-1)!;
        const expectedPage = Number(target.slice(1, 4));

        await page.route("**/api/search", respondWith([target]));
        await searchMeaning(page, "解約したらお金は戻りますか");

        await expect(page.locator(".pdf-finder-highlight").first()).toBeVisible();

        // Read from the document: the highlight span is rebuilt whenever the text layer re-renders.
        await expect
            .poll(async () =>
                page.evaluate(() => document.querySelector(".pdf-finder-highlight")?.closest(".pdf-finder-page")?.getAttribute("data-page-number") ?? null),
            )
            .toBe(String(expectedPage));
    });

    test("brings the passage itself into view, not just the top of its page", async ({ page }) => {
        // Scrolling to the page left a clause near its foot off-screen or clipped by the bottom
        // edge, so the reader had to hunt for the highlight the search had just found.
        await openFixture(page);
        const ids = await firstSegmentIds(page, 8);
        // The last segment of the first page, which is the one furthest down it.
        const target = ids.filter((id) => id.startsWith("p001")).at(-1)!;

        await page.route("**/api/search", respondWith([target]));
        await searchMeaning(page, "解約したらお金は戻りますか");
        await expect(page.locator(".pdf-finder-highlight").first()).toBeVisible();
        await page.waitForTimeout(800);

        const placement = await page.evaluate(() => {
            const node = document.querySelector(".pdf-finder-highlight");
            const pane = node?.closest(".overflow-y-auto");
            if (node == null || pane == null) return null;
            const box = node.getBoundingClientRect();
            const paneBox = pane.getBoundingClientRect();
            return { top: box.top - paneBox.top, bottom: paneBox.bottom - box.bottom, height: paneBox.height };
        });

        expect(placement).not.toBeNull();
        // Fully inside the pane, with room on both sides rather than jammed against an edge.
        expect(placement!.top).toBeGreaterThan(placement!.height * 0.2);
        expect(placement!.bottom).toBeGreaterThan(placement!.height * 0.2);
    });

    test("repeated text highlights the occurrence the selected result represents", async ({ page }) => {
        await openFixture(page);
        await searchExact(page, "返還は行わない");

        const resultCount = await page.locator("ol li").count();
        test.skip(resultCount < 2, "fixture has no repeated passage; see tests/fixtures/README.md");

        const first = await highlightText(page);
        const firstPosition = await highlightPosition(page);

        await page.getByRole("button", { name: "Next" }).click();
        await expect(page.locator(".pdf-finder-highlight").first()).toBeVisible();

        const second = await highlightText(page);
        const secondPosition = await highlightPosition(page);

        // Character-level ranges mean both occurrences mark exactly the query and nothing else,
        // so the marked text can no longer tell them apart — their positions have to. Folded
        // before comparing: this fixture writes 行 as its compatibility form, which is precisely
        // what normalization exists to see through.
        const marked = (text: string) => text.replace(/\s+/gu, "").normalize("NFKC");
        expect(marked(first)).toBe("返還は行わない");
        expect(marked(second)).toBe("返還は行わない");
        expect(Math.abs(secondPosition.top - firstPosition.top)).toBeGreaterThan(0.01);
    });

    test("folds halfwidth and decomposed Japanese through the real viewer", async ({ page }) => {
        // Unit tests pin the folding; this pins that the same folding is what the running
        // application applies to a query typed into the real search box.
        await openFixture(page);

        await searchExact(page, "サービス");
        await expect(page.locator("ol li")).not.toHaveCount(0);
        const baseline = await page.locator("ol li").count();

        // Halfwidth katakana: サ ー ヒ ゛ ス, with the dakuten as its own code point.
        await searchExact(page, "ｻｰﾋﾞｽ");
        await expect(page.locator("ol li")).toHaveCount(baseline);

        // The same word written with a combining dakuten instead of a precomposed ビ.
        await searchExact(page, "サーヒ\u3099ス");
        await expect(page.locator("ol li")).toHaveCount(baseline);

        // And a halfwidth handakuten, which folds the same way.
        await searchExact(page, "パーセント");
        const percent = await page.locator("ol li").count();
        test.skip(percent === 0, "fixture does not contain パーセント");
        await searchExact(page, "ﾊﾟｰｾﾝﾄ");
        await expect(page.locator("ol li")).toHaveCount(percent);
    });

    test("the highlight stays aligned at 100%, 125%, and 150% zoom", async ({ page }) => {
        await openFixture(page);
        const [target] = await firstSegmentIds(page, 1);

        await page.route("**/api/search", respondWith([target]));
        await searchMeaning(page, "解約の条件は");
        await expect(page.locator(".pdf-finder-highlight").first()).toBeVisible();

        // The viewer opens fitted to its pane, so 100% has to be selected before it can be the
        // baseline the spec's zoom levels are measured from.
        await setZoom(page, "100%");
        await page.waitForTimeout(500);

        const baseline = await highlightPosition(page);
        const spanCount = await page.locator(".pdf-finder-highlight").count();

        for (const expectedZoom of ["125%", "150%"]) {
            await page.getByRole("button", { name: "Zoom in" }).click();
            await expect(page.getByLabel("Zoom level")).toHaveText(expectedZoom);
            await page.waitForTimeout(500);

            const zoomed = await highlightPosition(page);

            // The highlight survives the zoom rather than being rebuilt.
            expect(await page.locator(".pdf-finder-highlight").count()).toBe(spanCount);
            // Its position relative to the page is unchanged, so canvas and text layer agree.
            expect(Math.abs(zoomed.left - baseline.left)).toBeLessThan(0.005);
            expect(Math.abs(zoomed.top - baseline.top)).toBeLessThan(0.005);
            expect(zoomed.pageWidth).toBeGreaterThan(baseline.pageWidth);
        }
    });

    test("zooming while pages are still loading leaves no page at the old scale", async ({ page }) => {
        // Regression: pages built after a zoom change kept the scale captured when the build
        // started, so they stayed at the old size and any highlight on them was misplaced.
        const client = await page.context().newCDPSession(page);
        await client.send("Emulation.setCPUThrottlingRate", { rate: 20 });

        await page.goto("/");
        await page.setInputFiles('input[type="file"]', FIXTURE);
        await page.waitForSelector(".pdf-finder-page");
        // Pinned rather than stepped: the fit-to-width scale depends on the window, so stepping
        // from it would not name a level this assertion could pin.
        await page.getByRole("button", { name: "Zoom out" }).click({ force: true });

        await client.send("Emulation.setCPUThrottlingRate", { rate: 1 });
        const settled = await page.getByLabel("Zoom level").textContent();
        expect(settled).not.toBeNull();
        await page.waitForTimeout(3000);

        const scales = await page
            .locator(".pdf-finder-page")
            .evaluateAll((nodes) => nodes.map((node) => getComputedStyle(node).getPropertyValue("--scale-factor").trim()));

        const expected = String(Number(settled!.replace("%", "")) / 100);
        expect(scales.length).toBeGreaterThan(0);
        expect([...new Set(scales)]).toEqual([expected]);
    });

    test("an uncertain search opens its highest ranked result and says it is uncertain", async ({ page }) => {
        await openFixture(page);
        const [target] = await firstSegmentIds(page, 1);

        await page.route("**/api/search", respondWith([target], "uncertain"));
        await searchMeaning(page, "解約の条件について");

        await expect(page.locator("ol li")).toHaveCount(1);
        await expect(page.getByText("may be related")).toBeVisible();
        await expect(page.locator(".pdf-finder-highlight").first()).toBeVisible();
        await expect(page.locator("ol li button[aria-current='true']")).toHaveCount(1);
    });

    test("a matched search opens the highest ranked result", async ({ page }) => {
        await openFixture(page);
        const [target] = await firstSegmentIds(page, 1);

        await page.route("**/api/search", respondWith([target]));
        await searchMeaning(page, "解約の条件について");

        await expect(page.locator(".pdf-finder-highlight").first()).toBeVisible();
        await expect(page.locator("ol li button[aria-current='true']")).toHaveCount(1);
    });

    test("an older response cannot replace newer results", async ({ page }) => {
        await openFixture(page);
        const ids = await firstSegmentIds(page, 2);

        let call = 0;
        await page.route("**/api/search", async (route) => {
            call += 1;
            if (call === 1) {
                // The superseded search answers late and with a stale requestId.
                await new Promise((resolve) => setTimeout(resolve, 1500));
                await route.fulfill({
                    contentType: "application/x-ndjson",
                    body:
                        JSON.stringify({
                            type: "final",
                            documentId: "stale-document",
                            requestId: "stale-request",
                            status: "matched",
                            results: [{ segmentId: ids[0], score: 2, relevantProbability: 0.99, confidence: 0.9 }],
                            evaluatedSegmentCount: 1,
                            requestCount: 1,
                            model: "jev-1.13.0",
                            elapsedMs: 1500,
                        }) + "\n",
                });
                return;
            }
            await respondWith([ids[1]])(route);
        });

        await searchMeaning(page, "最初の検索");
        await page.waitForTimeout(200);
        await searchMeaning(page, "二回目の検索");

        await expect(page.locator(".pdf-finder-highlight").first()).toBeVisible();
        await page.waitForTimeout(2000);

        // The newer search's result is still the one shown.
        const shown = await page.locator("ol li").count();
        expect(shown).toBe(1);
        await expect(page.locator("ol li").first()).toBeVisible();
    });

    test("replacing the PDF clears the previous document's results", async ({ page }) => {
        await openFixture(page);
        const [target] = await firstSegmentIds(page, 1);

        await page.route("**/api/search", respondWith([target]));
        await searchMeaning(page, "解約について");
        await expect(page.locator("ol li")).toHaveCount(1);

        await page.setInputFiles('input[type="file"]', FIXTURE);
        await page.waitForSelector(".pdf-finder-page");

        await expect(page.locator("ol li")).toHaveCount(0);
        await expect(page.locator(".pdf-finder-highlight")).toHaveCount(0);
    });

    test("an API failure shows a search error, not no match", async ({ page }) => {
        await openFixture(page);

        await page.route("**/api/search", async (route) => {
            await route.fulfill({
                status: 502,
                json: { error: { code: "provider_unavailable", message: "The search could not be completed." } },
            });
        });

        await searchMeaning(page, "解約したらお金は戻りますか");

        await expect(page.getByText("The search could not be completed")).toBeVisible();
        await expect(page.getByText("met the relevance threshold")).toHaveCount(0);
        await expect(page.getByText("No matching text was found")).toHaveCount(0);
    });

    test("shows the model's own judgement on a meaning result and nothing of the kind on an exact one", async ({ page }) => {
        // §3: the numbers are shown because §14.19 found the same passage crossing all three §7
        // bands depending on its request. A reader who cannot see them cannot tell a passage the
        // model was sure of from one that scraped into the list.
        await openFixture(page);
        const [target] = await firstSegmentIds(page, 1);

        await page.route("**/api/search", respondWith([target]));
        await searchMeaning(page, "解約の条件について");
        await expect(page.locator("ol li")).toHaveCount(1);

        const item = page.locator("ol li").first();
        // 0.95 and 0.8 are what the mocked provider returned for this passage.
        await expect(item).toContainText("95%");
        await expect(item).toContainText("confident");
        await expect(item).toContainText("certainty 0.80");
        // Never as a similarity measurement: §3 still forbids "98% match", and the caveat is on
        // screen in text rather than behind a hover.
        await expect(page.getByText(/\d+% match/u)).toHaveCount(0);
        await expect(page.getByText("Model judgment")).toBeVisible();
        await expect(page.getByText("Not a measured match")).toBeVisible();

        // Exact search produces no judgement, so nothing of the kind may appear.
        await searchExact(page, "第");
        await expect(page.locator("ol li").first()).not.toContainText("certainty");
    });

    test("emphasises only the query terms that literally appear in a passage", async ({ page }) => {
        await openFixture(page);

        // Exact search: every result contains the query, so every preview carries the emphasis.
        await searchExact(page, "返還");
        await expect(page.locator("ol li")).not.toHaveCount(0);
        await expect(page.locator("ol li mark").first()).toHaveText("返還");

        // A query too short to be a term emphasises nothing rather than the whole passage.
        await searchExact(page, "第");
        await expect(page.locator("ol li")).not.toHaveCount(0);
        await expect(page.locator("ol li mark")).toHaveCount(0);

        // A query whose words appear nowhere emphasises nothing rather than guessing. Exact search
        // finds no result for it either, so the meaning path supplies the passage.
        const [target] = await firstSegmentIds(page, 1);
        await page.route("**/api/search", respondWith([target]));
        await searchMeaning(page, "ばらの花の育てかた");
        await expect(page.locator("ol li")).toHaveCount(1);
        await expect(page.locator("ol li mark")).toHaveCount(0);
    });

    test("reports what the last meaning search cost, in questions and in requests", async ({ page }) => {
        await openFixture(page);
        const [target] = await firstSegmentIds(page, 1);
        const segmentCount = Number((await page.locator("footer p").textContent())?.match(/(\d+) searchable segments/u)?.[1]);

        await page.route("**/api/search", respondWith([target]));
        await searchMeaning(page, "解約の条件について");

        // One question per segment, in the number of requests the response declared. The two bill
        // separately, so neither can be derived from the other.
        await expect(page.locator("footer p")).toContainText(`${segmentCount} Jev questions in 3 API calls`);
    });

    test("opens the viewer fitted to its pane, and Fit returns to it after zooming", async ({ page }) => {
        await openFixture(page);

        const fitted = (await page.getByLabel("Zoom level").textContent()) ?? "";
        // The pane is wider than a page at 100%, so fitting it is a different number.
        expect(fitted).not.toBe("100%");
        await expect(page.getByRole("button", { name: "Fit" })).toHaveAttribute("aria-pressed", "true");

        await setZoom(page, "100%");
        await expect(page.getByRole("button", { name: "Fit" })).toHaveAttribute("aria-pressed", "false");

        await page.getByRole("button", { name: "Fit" }).click();
        await expect(page.getByLabel("Zoom level")).toHaveText(fitted);
    });

    test("names the page currently in view", async ({ page }) => {
        await openFixture(page);
        await expect(page.getByText(/^1 \/ \d+$/u)).toBeVisible();

        // Scrolling the viewer, not the window: the pages live in their own scroll container.
        await page.locator(".pdf-finder-page").nth(1).scrollIntoViewIfNeeded();
        await expect(page.getByText(/^2 \/ \d+$/u)).toBeVisible();
    });

    test("the divider resizes the results panel", async ({ page }) => {
        await openFixture(page);

        const panel = page.locator("aside");
        const before = (await panel.boundingBox())!.width;

        const divider = page.getByRole("separator", { name: "Resize results panel" });
        const handle = (await divider.boundingBox())!;
        await page.mouse.move(handle.x + handle.width / 2, handle.y + handle.height / 2);
        await page.mouse.down();
        await page.mouse.move(handle.x + handle.width / 2 + 80, handle.y + handle.height / 2, { steps: 8 });
        await page.mouse.up();

        const dragged = (await panel.boundingBox())!.width;
        expect(dragged).toBeGreaterThan(before + 40);

        // A pointer drag is not an accessible control on its own.
        await divider.focus();
        await divider.press("ArrowLeft");
        expect((await panel.boundingBox())!.width).toBeLessThan(dragged);
    });

    test("states what meaning search sends, without a dialog to dismiss", async ({ page }) => {
        await openFixture(page);
        const [target] = await firstSegmentIds(page, 1);
        await page.route("**/api/search", respondWith([target]));

        // Exact search sends nothing, so the notice belongs to the meaning mode only.
        await page.getByRole("radio", { name: "Exact text" }).click();
        await expect(page.getByText("Sends your query and the extracted text to TypeSafe AI.")).toHaveCount(0);

        await page.getByRole("radio", { name: "Meaning" }).click();
        await expect(page.getByText("Sends your query and the extracted text to TypeSafe AI.")).toBeVisible();

        // The full disclosure is one hover away, and says which service and on what condition.
        await page.getByRole("button", { name: "About meaning search" }).hover();
        await expect(page.getByText("Use only documents you are permitted to send.")).toBeVisible();

        // Nothing has to be acknowledged first.
        await page.getByLabel("Search query").fill("解約について");
        await page.getByRole("button", { name: "Search", exact: true }).click();
        await expect(page.locator("ol li")).toHaveCount(1);
        await expect(page.getByRole("button", { name: "Continue" })).toHaveCount(0);
    });
});
