/**
 * Viewer and search behaviour in a real browser (spec §11.2).
 *
 * `/api/search` is intercepted throughout, so every functional requirement here is exercised
 * without a TypeSafe credential. That also makes the concurrency requirements testable, since a
 * response can be delayed deliberately.
 *
 * These tests need a fixture PDF. See `tests/fixtures/README.md`.
 */
import { expect, test } from "@playwright/test";
import type { Page, Route } from "@playwright/test";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));

/**
 * The document these tests drive.
 *
 * `sample-contract-ja.pdf` is generated by `npm run fixtures:sample` and is a development aid, not
 * one of the acceptance fixtures in `tests/fixtures/README.md`. It carries the three properties
 * these tests need: a clause that answers a refund question without using the word the reader
 * would type, a sentence repeated on two different pages, and enough pages that zooming during a
 * load is reproducible. An acceptance fixture is preferred when one is present.
 */
const FIXTURE =
    process.env.PDF_FINDER_FIXTURE ??
    [resolve(here, "fixtures/contract-ja.pdf"), resolve(here, "fixtures/sample-contract-ja.pdf")].find((path) => existsSync(path)) ??
    resolve(here, "fixtures/sample-contract-ja.pdf");

/**
 * Always runs, and fails loudly when the fixtures are missing.
 *
 * Without it the whole suite would go green while testing nothing, which is exactly the
 * mock-only-success trap this repository's instructions warn about.
 */
test("fixture PDFs are present", () => {
    expect(existsSync(FIXTURE), `Fixture PDF missing: ${FIXTURE}. See tests/fixtures/README.md. Every other test in this file is skipped.`).toBe(true);
});

test.describe("appearance", () => {
    // Spec §3 asks for a quiet, light design. The starter this project grew from followed the
    // system preference, so a reader on a dark desktop saw a dark application.
    test("looks the same whether the system prefers light or dark", async ({ browser }) => {
        const sample = async (colorScheme: "light" | "dark") => {
            const context = await browser.newContext({ colorScheme });
            const page = await context.newPage();
            await page.goto("/");
            await page.waitForSelector("h1");

            const result = await page.evaluate(() => {
                const style = getComputedStyle(document.documentElement);
                return {
                    darkClass: document.documentElement.classList.contains("dark-mode"),
                    colorScheme: style.colorScheme,
                    body: getComputedStyle(document.body).backgroundColor,
                    heading: getComputedStyle(document.querySelector("h1")!).color,
                    openPdf: getComputedStyle(document.querySelector("label span")!).backgroundColor,
                };
            });

            await context.close();
            return result;
        };

        const light = await sample("light");
        const dark = await sample("dark");

        // Nothing about the page may depend on the preference.
        expect(dark).toEqual(light);
        expect(dark.darkClass).toBe(false);
        // Pinned so native controls such as scrollbars cannot follow the dark preference either.
        expect(dark.colorScheme).toBe("light");
        expect(dark.body).toBe("rgb(255, 255, 255)");
    });
});

test.describe("viewer", () => {
    test.skip(() => !existsSync(FIXTURE), "fixture PDF not present");

    const openFixture = async (page: Page) => {
        await page.goto("/");
        await page.setInputFiles('input[type="file"]', FIXTURE);
        await page.waitForSelector(".pdf-finder-page");
        await page.waitForFunction(() => document.querySelectorAll(".textLayer span").length > 10);
    };

    const searchExact = async (page: Page, query: string) => {
        await page.locator('label:has-text("Exact text")').click();
        await page.getByLabel("Search query").fill(query);
        await page.getByRole("button", { name: "Search" }).click();
    };

    /** Runs a meaning search, accepting the disclosure the first time it appears. */
    const searchMeaning = async (page: Page, query: string) => {
        await page.locator('label:has-text("Meaning")').click();
        await page.getByLabel("Search query").fill(query);
        await page.getByRole("button", { name: "Search" }).click();
    };

    const highlightText = (page: Page) => page.locator(".pdf-finder-highlight").evaluateAll((nodes) => nodes.map((node) => node.textContent).join(""));

    /**
     * Highlight position as a fraction of its page box, so it is comparable across zoom levels.
     *
     * Both rectangles are read inside one evaluation: fetching them in separate round-trips lets a
     * smooth scroll move one of them in between, which shows up as alignment drift that is not
     * there.
     */
    const highlightPosition = (page: Page) =>
        page
            .locator(".pdf-finder-highlight")
            .first()
            .evaluate((node) => {
                const pageBox = node.closest(".pdf-finder-page")!.getBoundingClientRect();
                const box = node.getBoundingClientRect();

                return {
                    left: (box.left - pageBox.left) / pageBox.width,
                    top: (box.top - pageBox.top) / pageBox.height,
                    pageWidth: pageBox.width,
                };
            });

    const respondWith =
        (results: string[], status = "matched") =>
        async (route: Route) => {
            const body = JSON.parse(route.request().postData() ?? "{}") as { documentId: string; requestId: string };
            await route.fulfill({
                json: {
                    documentId: body.documentId,
                    requestId: body.requestId,
                    status,
                    results: results.map((segmentId, index) => ({
                        segmentId,
                        score: 1.9 - index * 0.1,
                        relevantProbability: 0.95 - index * 0.05,
                        confidence: 0.8,
                    })),
                    evaluatedSegmentCount: results.length,
                    model: "jev-1.13.0",
                    elapsedMs: 120,
                },
            });
        };

    const firstSegmentIds = async (page: Page, count: number): Promise<string[]> => {
        await page.getByRole("button", { name: "View extracted text" }).click();
        const ids = await page.locator("article header").evaluateAll((nodes) => nodes.map((node) => node.textContent?.match(/p\d{3}-s\d{3}/u)?.[0] ?? ""));
        await page.getByRole("button", { name: "Hide extracted text" }).click();
        return ids.filter((id) => id !== "").slice(0, count);
    };

    test("renders the document and reports what it extracted", async ({ page }) => {
        await openFixture(page);

        await expect(page.locator(".pdf-finder-page")).not.toHaveCount(0);
        await expect(page.locator("footer p")).toContainText("searchable segments");
    });

    test("exact mode makes no request to the semantic-search endpoint", async ({ page }) => {
        let called = false;
        await page.route("**/api/search", async (route) => {
            called = true;
            await route.abort();
        });

        await openFixture(page);
        await searchExact(page, "解約");
        await page.waitForTimeout(1000);

        expect(called).toBe(false);
    });

    test("selecting a result navigates to its physical page", async ({ page }) => {
        await openFixture(page);
        const ids = await firstSegmentIds(page, 3);
        const target = ids.at(-1)!;
        const expectedPage = Number(target.slice(1, 4));

        await page.route("**/api/search", respondWith([target]));
        await searchMeaning(page, "解約したらお金は戻りますか");

        await expect(page.locator(".pdf-finder-highlight").first()).toBeVisible();
        const pageNumber = await page
            .locator(".pdf-finder-highlight")
            .first()
            .evaluate((node) => node.closest(".pdf-finder-page")?.getAttribute("data-page-number"));

        expect(Number(pageNumber)).toBe(expectedPage);
    });

    test("repeated text highlights the occurrence the selected result represents", async ({ page }) => {
        await openFixture(page);
        await searchExact(page, "返還は行わない");

        const resultCount = await page.locator("ol li").count();
        test.skip(resultCount < 2, "fixture has no repeated passage; see tests/fixtures/README.md");

        const first = await highlightText(page);
        const firstPosition = await highlightPosition(page);

        await page.getByRole("button", { name: "Next" }).click();
        await expect(page.locator(".pdf-finder-highlight").first()).toBeVisible();

        const second = await highlightText(page);
        const secondPosition = await highlightPosition(page);

        expect(second).not.toBe(first);
        expect(Math.abs(secondPosition.top - firstPosition.top)).toBeGreaterThan(0.01);
    });

    test("the highlight stays aligned at 100%, 125%, and 150% zoom", async ({ page }) => {
        await openFixture(page);
        const [target] = await firstSegmentIds(page, 1);

        await page.route("**/api/search", respondWith([target]));
        await searchMeaning(page, "解約の条件は");
        await expect(page.locator(".pdf-finder-highlight").first()).toBeVisible();

        const baseline = await highlightPosition(page);
        const spanCount = await page.locator(".pdf-finder-highlight").count();

        for (const expectedZoom of ["125%", "150%"]) {
            await page.getByRole("button", { name: "Zoom in" }).click();
            await expect(page.locator("span.w-14")).toHaveText(expectedZoom);
            await page.waitForTimeout(500);

            const zoomed = await highlightPosition(page);

            // The highlight survives the zoom rather than being rebuilt.
            expect(await page.locator(".pdf-finder-highlight").count()).toBe(spanCount);
            // Its position relative to the page is unchanged, so canvas and text layer agree.
            expect(Math.abs(zoomed.left - baseline.left)).toBeLessThan(0.005);
            expect(Math.abs(zoomed.top - baseline.top)).toBeLessThan(0.005);
            expect(zoomed.pageWidth).toBeGreaterThan(baseline.pageWidth);
        }
    });

    test("zooming while pages are still loading leaves no page at the old scale", async ({ page }) => {
        // Regression: pages built after a zoom change kept the scale captured when the build
        // started, so they stayed at the old size and any highlight on them was misplaced.
        const client = await page.context().newCDPSession(page);
        await client.send("Emulation.setCPUThrottlingRate", { rate: 20 });

        await page.goto("/");
        await page.setInputFiles('input[type="file"]', FIXTURE);
        await page.waitForSelector(".pdf-finder-page");
        await page.getByRole("button", { name: "Zoom in" }).click({ force: true });

        await client.send("Emulation.setCPUThrottlingRate", { rate: 1 });
        await expect(page.locator("span.w-14")).toHaveText("125%");
        await page.waitForTimeout(3000);

        const scales = await page
            .locator(".pdf-finder-page")
            .evaluateAll((nodes) => nodes.map((node) => getComputedStyle(node).getPropertyValue("--scale-factor").trim()));

        expect(scales.length).toBeGreaterThan(0);
        expect([...new Set(scales)]).toEqual(["1.25"]);
    });

    test("an uncertain search opens its highest ranked result and says it is uncertain", async ({ page }) => {
        await openFixture(page);
        const [target] = await firstSegmentIds(page, 1);

        await page.route("**/api/search", respondWith([target], "uncertain"));
        await searchMeaning(page, "解約の条件について");

        await expect(page.locator("ol li")).toHaveCount(1);
        await expect(page.getByText("may be related")).toBeVisible();
        await expect(page.locator(".pdf-finder-highlight").first()).toBeVisible();
        await expect(page.locator("ol li button[aria-current='true']")).toHaveCount(1);
    });

    test("a matched search opens the highest ranked result", async ({ page }) => {
        await openFixture(page);
        const [target] = await firstSegmentIds(page, 1);

        await page.route("**/api/search", respondWith([target]));
        await searchMeaning(page, "解約の条件について");

        await expect(page.locator(".pdf-finder-highlight").first()).toBeVisible();
        await expect(page.locator("ol li button[aria-current='true']")).toHaveCount(1);
    });

    test("an older response cannot replace newer results", async ({ page }) => {
        await openFixture(page);
        const ids = await firstSegmentIds(page, 2);

        let call = 0;
        await page.route("**/api/search", async (route) => {
            call += 1;
            if (call === 1) {
                // The superseded search answers late and with a stale requestId.
                await new Promise((resolve) => setTimeout(resolve, 1500));
                await route.fulfill({
                    json: {
                        documentId: "stale-document",
                        requestId: "stale-request",
                        status: "matched",
                        results: [{ segmentId: ids[0], score: 2, relevantProbability: 0.99, confidence: 0.9 }],
                        evaluatedSegmentCount: 1,
                        model: "jev-1.13.0",
                        elapsedMs: 1500,
                    },
                });
                return;
            }
            await respondWith([ids[1]])(route);
        });

        await searchMeaning(page, "最初の検索");
        await page.waitForTimeout(200);
        await searchMeaning(page, "二回目の検索");

        await expect(page.locator(".pdf-finder-highlight").first()).toBeVisible();
        await page.waitForTimeout(2000);

        // The newer search's result is still the one shown.
        const shown = await page.locator("ol li").count();
        expect(shown).toBe(1);
        await expect(page.locator("ol li").first()).toBeVisible();
    });

    test("replacing the PDF clears the previous document's results", async ({ page }) => {
        await openFixture(page);
        const [target] = await firstSegmentIds(page, 1);

        await page.route("**/api/search", respondWith([target]));
        await searchMeaning(page, "解約について");
        await expect(page.locator("ol li")).toHaveCount(1);

        await page.setInputFiles('input[type="file"]', FIXTURE);
        await page.waitForSelector(".pdf-finder-page");

        await expect(page.locator("ol li")).toHaveCount(0);
        await expect(page.locator(".pdf-finder-highlight")).toHaveCount(0);
    });

    test("an API failure shows a search error, not no match", async ({ page }) => {
        await openFixture(page);

        await page.route("**/api/search", async (route) => {
            await route.fulfill({
                status: 502,
                json: { error: { code: "provider_unavailable", message: "The search could not be completed." } },
            });
        });

        await searchMeaning(page, "解約したらお金は戻りますか");

        await expect(page.getByText("The search could not be completed")).toBeVisible();
        await expect(page.getByText("No relevant passage was found")).toHaveCount(0);
    });

    test("states what meaning search sends, without a dialog to dismiss", async ({ page }) => {
        await openFixture(page);
        const [target] = await firstSegmentIds(page, 1);
        await page.route("**/api/search", respondWith([target]));

        // Exact search sends nothing, so the notice belongs to the meaning mode only.
        await page.locator('label:has-text("Exact text")').click();
        await expect(page.getByText("sends your query and text extracted from the PDF")).toHaveCount(0);

        await page.locator('label:has-text("Meaning")').click();
        await expect(page.getByText("sends your query and text extracted from the PDF")).toBeVisible();

        // Nothing has to be acknowledged first.
        await page.getByLabel("Search query").fill("解約について");
        await page.getByRole("button", { name: "Search" }).click();
        await expect(page.locator("ol li")).toHaveCount(1);
        await expect(page.getByRole("button", { name: "Continue" })).toHaveCount(0);
    });
});
