/**
 * Viewer and search behaviour in a real browser (spec §11.2).
 *
 * `/api/search` is intercepted throughout, so every functional requirement here is exercised
 * without a TypeSafe credential. That also makes the concurrency requirements testable, since a
 * response can be delayed deliberately.
 *
 * These tests need a fixture PDF. See `tests/fixtures/README.md`.
 */
import { expect, test } from "@playwright/test";
import type { Page, Route } from "@playwright/test";
import { existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { installControlledStream, releaseFinalLine, releaseNextProgress } from "./controlled-stream";

const here = dirname(fileURLToPath(import.meta.url));

/**
 * The document these tests drive.
 *
 * `sample-contract-ja.pdf` is generated by `npm run fixtures:sample` and is a development aid, not
 * one of the acceptance fixtures in `tests/fixtures/README.md`. It carries the three properties
 * these tests need: a clause that answers a refund question without using the word the reader
 * would type, a sentence repeated on two different pages, and enough pages that zooming during a
 * load is reproducible. An acceptance fixture is preferred when one is present.
 */
const FIXTURE =
    process.env.PDF_FINDER_FIXTURE ??
    [resolve(here, "fixtures/contract-ja.pdf"), resolve(here, "fixtures/sample-contract-ja.pdf")].find((path) => existsSync(path)) ??
    resolve(here, "fixtures/sample-contract-ja.pdf");

/**
 * Always runs, and fails loudly when the fixtures are missing.
 *
 * Without it the whole suite would go green while testing nothing, which is exactly the
 * mock-only-success trap this repository's instructions warn about.
 */
test("fixture PDFs are present", () => {
    expect(existsSync(FIXTURE), `Fixture PDF missing: ${FIXTURE}. See tests/fixtures/README.md. Every other test in this file is skipped.`).toBe(true);
});

test.describe("appearance", () => {
    // Spec §3 asks for a quiet, light design. The starter this project grew from followed the
    // system preference, so a reader on a dark desktop saw a dark application.
    test("looks the same whether the system prefers light or dark", async ({ browser }) => {
        const sample = async (colorScheme: "light" | "dark") => {
            const context = await browser.newContext({ colorScheme });
            const page = await context.newPage();
            await page.goto("/");
            await page.waitForSelector("h1");

            const result = await page.evaluate(() => {
                const style = getComputedStyle(document.documentElement);
                return {
                    darkClass: document.documentElement.classList.contains("dark-mode"),
                    colorScheme: style.colorScheme,
                    body: getComputedStyle(document.body).backgroundColor,
                    heading: getComputedStyle(document.querySelector("h1")!).color,
                    // The drop zone is the only control on an empty page; the header's Open PDF
                    // button appears only once a document is loaded.
                    dropZone: getComputedStyle(document.querySelector("[data-dropzone]")!).backgroundColor,
                };
            });

            await context.close();
            return result;
        };

        const light = await sample("light");
        const dark = await sample("dark");

        // Nothing about the page may depend on the preference.
        expect(dark).toEqual(light);
        expect(dark.darkClass).toBe(false);
        // Pinned so native controls such as scrollbars cannot follow the dark preference either.
        expect(dark.colorScheme).toBe("light");
        expect(dark.body).toBe("rgb(255, 255, 255)");
    });
});

test.describe("viewer", () => {
    test.skip(() => !existsSync(FIXTURE), "fixture PDF not present");

    const openFixture = async (page: Page) => {
        await page.goto("/");
        await page.setInputFiles('input[type="file"]', FIXTURE);
        await page.waitForSelector(".pdf-finder-page");
        await page.waitForFunction(() => document.querySelectorAll(".textLayer span").length > 10);
    };

    const searchExact = async (page: Page, query: string) => {
        await page.getByRole("radio", { name: "Exact text" }).click();
        await page.getByLabel("Search query").fill(query);
        await page.getByRole("button", { name: "Search", exact: true }).click();
    };

    const searchMeaning = async (page: Page, query: string) => {
        await page.getByRole("radio", { name: "Meaning" }).click();
        await page.getByLabel("Search query").fill(query);
        await page.getByRole("button", { name: "Search", exact: true }).click();
    };

    /** Steps the zoom ladder until the label reads the requested level. */
    const setZoom = async (page: Page, target: string) => {
        for (let attempt = 0; attempt < 12; attempt += 1) {
            const current = (await page.getByLabel("Zoom level").textContent()) ?? "";
            if (current === target) return;
            const direction = Number(current.replace("%", "")) > Number(target.replace("%", "")) ? "Zoom out" : "Zoom in";
            await page.getByRole("button", { name: direction }).click();
        }
        throw new Error(`zoom never reached ${target}`);
    };

    const highlightText = (page: Page) => page.locator(".pdf-finder-highlight").evaluateAll((nodes) => nodes.map((node) => node.textContent).join(""));

    /**
     * Highlight position as a fraction of its page box, so it is comparable across zoom levels.
     *
     * Read from the document rather than through a resolved element handle. An exact-search
     * highlight is a span *inside* a text-layer element, and the effect that applies it tears the
     * span down and rebuilds it whenever the layer re-renders — so a handle resolved a moment
     * earlier can already be detached, and `closest()` returns null. Polling until a whole reading
     * succeeds measures the highlight that is actually on screen.
     *
     * Both rectangles are read inside one evaluation: fetching them in separate round-trips lets a
     * smooth scroll move one of them in between, which shows up as alignment drift that is not
     * there.
     */
    const highlightPosition = async (page: Page) => {
        const read = () =>
            page.evaluate(() => {
                const node = document.querySelector(".pdf-finder-highlight");
                const pageElement = node?.closest(".pdf-finder-page");
                if (node == null || pageElement == null) return null;

                const pageBox = pageElement.getBoundingClientRect();
                const box = node.getBoundingClientRect();
                if (pageBox.width === 0) return null;

                return {
                    left: (box.left - pageBox.left) / pageBox.width,
                    top: (box.top - pageBox.top) / pageBox.height,
                    pageWidth: pageBox.width,
                };
            });

        for (let attempt = 0; attempt < 30; attempt += 1) {
            const measured = await read();
            if (measured !== null) return measured;
            await page.waitForTimeout(100);
        }

        throw new Error("no highlight was on screen to measure");
    };

    const respondWith =
        (results: string[], status = "matched") =>
        async (route: Route) => {
            const body = JSON.parse(route.request().postData() ?? "{}") as { documentId: string; requestId: string; segments: { id: string }[] };
            await route.fulfill({
                contentType: "application/x-ndjson",
                body:
                    JSON.stringify({
                        type: "final",
                        documentId: body.documentId,
                        requestId: body.requestId,
                        status,
                        results: results.map((segmentId, index) => ({
                            segmentId,
                            score: 1.9 - index * 0.1,
                            relevantProbability: 0.95 - index * 0.05,
                            confidence: 0.8,
                        })),
                        evaluatedSegmentCount: body.segments.length,
                        requestCount: 3,
                        model: "jev-1.13.0",
                        elapsedMs: 120,
                    }) + "\n",
            });
        };

    const firstSegmentIds = async (page: Page, count: number): Promise<string[]> => {
        await page.getByRole("button", { name: "View extracted text" }).click();
        const ids = await page.locator("article header").evaluateAll((nodes) => nodes.map((node) => node.textContent?.match(/p\d{3}-s\d{3}/u)?.[0] ?? ""));
        await page.getByRole("button", { name: "Hide extracted text" }).click();
        return ids.filter((id) => id !== "").slice(0, count);
    };

    test("renders the document and reports what it extracted", async ({ page }) => {
        await openFixture(page);

        await expect(page.locator(".pdf-finder-page")).not.toHaveCount(0);
        await expect(page.locator("footer p")).toContainText("searchable segments");
    });

    test("exact mode makes no request to the semantic-search endpoint", async ({ page }) => {
        let called = false;
        await page.route("**/api/search", async (route) => {
            called = true;
            await route.abort();
        });

        await openFixture(page);
        await searchExact(page, "解約");
        await page.waitForTimeout(1000);

        expect(called).toBe(false);
    });

    test("selecting a result navigates to its physical page", async ({ page }) => {
        await openFixture(page);
        const ids = await firstSegmentIds(page, 3);
        const target = ids.at(-1)!;
        const expectedPage = Number(target.slice(1, 4));

        await page.route("**/api/search", respondWith([target]));
        await searchMeaning(page, "解約したらお金は戻りますか");

        await expect(page.locator(".pdf-finder-highlight").first()).toBeVisible();

        // Read from the document: the highlight span is rebuilt whenever the text layer re-renders.
        await expect
            .poll(async () =>
                page.evaluate(() => document.querySelector(".pdf-finder-highlight")?.closest(".pdf-finder-page")?.getAttribute("data-page-number") ?? null),
            )
            .toBe(String(expectedPage));
    });

    test("brings the passage itself into view, not just the top of its page", async ({ page }) => {
        // Scrolling to the page left a clause near its foot off-screen or clipped by the bottom
        // edge, so the reader had to hunt for the highlight the search had just found.
        await openFixture(page);
        const ids = await firstSegmentIds(page, 8);
        // The last segment of the first page, which is the one furthest down it.
        const target = ids.filter((id) => id.startsWith("p001")).at(-1)!;

        await page.route("**/api/search", respondWith([target]));
        await searchMeaning(page, "解約したらお金は戻りますか");
        await expect(page.locator(".pdf-finder-highlight").first()).toBeVisible();
        await page.waitForTimeout(800);

        const placement = await page.evaluate(() => {
            const node = document.querySelector(".pdf-finder-highlight");
            const pane = node?.closest(".overflow-y-auto");
            if (node == null || pane == null) return null;
            const box = node.getBoundingClientRect();
            const paneBox = pane.getBoundingClientRect();
            return { top: box.top - paneBox.top, bottom: paneBox.bottom - box.bottom, height: paneBox.height };
        });

        expect(placement).not.toBeNull();
        // Fully inside the pane, with room on both sides rather than jammed against an edge.
        expect(placement!.top).toBeGreaterThan(placement!.height * 0.2);
        expect(placement!.bottom).toBeGreaterThan(placement!.height * 0.2);
    });

    test("repeated text highlights the occurrence the selected result represents", async ({ page }) => {
        await openFixture(page);
        await searchExact(page, "返還は行わない");

        const resultCount = await page.locator("ol li").count();
        test.skip(resultCount < 2, "fixture has no repeated passage; see tests/fixtures/README.md");

        const first = await highlightText(page);
        const firstPosition = await highlightPosition(page);

        await page.getByRole("button", { name: "Next" }).click();
        await expect(page.locator(".pdf-finder-highlight").first()).toBeVisible();

        const second = await highlightText(page);
        const secondPosition = await highlightPosition(page);

        // Character-level ranges mean both occurrences mark exactly the query and nothing else,
        // so the marked text can no longer tell them apart — their positions have to. Folded
        // before comparing: this fixture writes 行 as its compatibility form, which is precisely
        // what normalization exists to see through.
        const marked = (text: string) => text.replace(/\s+/gu, "").normalize("NFKC");
        expect(marked(first)).toBe("返還は行わない");
        expect(marked(second)).toBe("返還は行わない");
        expect(Math.abs(secondPosition.top - firstPosition.top)).toBeGreaterThan(0.01);
    });

    test("folds halfwidth and decomposed Japanese through the real viewer", async ({ page }) => {
        // Unit tests pin the folding; this pins that the same folding is what the running
        // application applies to a query typed into the real search box.
        await openFixture(page);

        await searchExact(page, "サービス");
        await expect(page.locator("ol li")).not.toHaveCount(0);
        const baseline = await page.locator("ol li").count();

        // Halfwidth katakana: サ ー ヒ ゛ ス, with the dakuten as its own code point.
        await searchExact(page, "ｻｰﾋﾞｽ");
        await expect(page.locator("ol li")).toHaveCount(baseline);

        // The same word written with a combining dakuten instead of a precomposed ビ.
        await searchExact(page, "サーヒ\u3099ス");
        await expect(page.locator("ol li")).toHaveCount(baseline);

        // And a halfwidth handakuten, which folds the same way.
        await searchExact(page, "パーセント");
        const percent = await page.locator("ol li").count();
        test.skip(percent === 0, "fixture does not contain パーセント");
        await searchExact(page, "ﾊﾟｰｾﾝﾄ");
        await expect(page.locator("ol li")).toHaveCount(percent);
    });

    test("the highlight stays aligned at 100%, 125%, and 150% zoom", async ({ page }) => {
        await openFixture(page);
        const [target] = await firstSegmentIds(page, 1);

        await page.route("**/api/search", respondWith([target]));
        await searchMeaning(page, "解約の条件は");
        await expect(page.locator(".pdf-finder-highlight").first()).toBeVisible();

        // The viewer opens fitted to its pane, so 100% has to be selected before it can be the
        // baseline the spec's zoom levels are measured from.
        await setZoom(page, "100%");
        await page.waitForTimeout(500);

        const baseline = await highlightPosition(page);
        const spanCount = await page.locator(".pdf-finder-highlight").count();

        for (const expectedZoom of ["125%", "150%"]) {
            await page.getByRole("button", { name: "Zoom in" }).click();
            await expect(page.getByLabel("Zoom level")).toHaveText(expectedZoom);
            await page.waitForTimeout(500);

            const zoomed = await highlightPosition(page);

            // The highlight survives the zoom rather than being rebuilt.
            expect(await page.locator(".pdf-finder-highlight").count()).toBe(spanCount);
            // Its position relative to the page is unchanged, so canvas and text layer agree.
            expect(Math.abs(zoomed.left - baseline.left)).toBeLessThan(0.005);
            expect(Math.abs(zoomed.top - baseline.top)).toBeLessThan(0.005);
            expect(zoomed.pageWidth).toBeGreaterThan(baseline.pageWidth);
        }
    });

    test("zooming while pages are still loading leaves no page at the old scale", async ({ page }) => {
        // Regression: pages built after a zoom change kept the scale captured when the build
        // started, so they stayed at the old size and any highlight on them was misplaced.
        const client = await page.context().newCDPSession(page);
        await client.send("Emulation.setCPUThrottlingRate", { rate: 20 });

        await page.goto("/");
        await page.setInputFiles('input[type="file"]', FIXTURE);
        await page.waitForSelector(".pdf-finder-page");
        // Pinned rather than stepped: the fit-to-width scale depends on the window, so stepping
        // from it would not name a level this assertion could pin.
        await page.getByRole("button", { name: "Zoom out" }).click({ force: true });

        await client.send("Emulation.setCPUThrottlingRate", { rate: 1 });
        const settled = await page.getByLabel("Zoom level").textContent();
        expect(settled).not.toBeNull();
        await page.waitForTimeout(3000);

        const scales = await page
            .locator(".pdf-finder-page")
            .evaluateAll((nodes) => nodes.map((node) => getComputedStyle(node).getPropertyValue("--scale-factor").trim()));

        const expected = String(Number(settled!.replace("%", "")) / 100);
        expect(scales.length).toBeGreaterThan(0);
        expect([...new Set(scales)]).toEqual([expected]);
    });

    test("an uncertain search offers no passage, and says one came close", async ({ page }) => {
        // §7: a passage below the matched threshold is not a candidate. It used to arrive in the
        // same list, in the same shape, as one the model was confident of, under a note the reader
        // had already passed by the time it mattered.
        await openFixture(page);

        await page.route("**/api/search", respondWith([], "uncertain"));
        await searchMeaning(page, "解約の条件について");

        await expect(page.locator("ol li")).toHaveCount(0);
        await expect(page.locator(".pdf-finder-highlight")).toHaveCount(0);
        await expect(page.getByText("came close to the relevance threshold")).toBeVisible();
    });

    test("a matched search opens the highest ranked result", async ({ page }) => {
        await openFixture(page);
        const [target] = await firstSegmentIds(page, 1);

        await page.route("**/api/search", respondWith([target]));
        await searchMeaning(page, "解約の条件について");

        await expect(page.locator(".pdf-finder-highlight").first()).toBeVisible();
        await expect(page.locator("ol li button[aria-current='true']")).toHaveCount(1);
    });

    test("an older response cannot replace newer results", async ({ page }) => {
        await openFixture(page);
        const ids = await firstSegmentIds(page, 2);

        let call = 0;
        await page.route("**/api/search", async (route) => {
            call += 1;
            if (call === 1) {
                // The superseded search answers late and with a stale requestId.
                await new Promise((resolve) => setTimeout(resolve, 1500));
                await route.fulfill({
                    contentType: "application/x-ndjson",
                    body:
                        JSON.stringify({
                            type: "final",
                            documentId: "stale-document",
                            requestId: "stale-request",
                            status: "matched",
                            results: [{ segmentId: ids[0], score: 2, relevantProbability: 0.99, confidence: 0.9 }],
                            evaluatedSegmentCount: 1,
                            requestCount: 1,
                            model: "jev-1.13.0",
                            elapsedMs: 1500,
                        }) + "\n",
                });
                return;
            }
            await respondWith([ids[1]])(route);
        });

        await searchMeaning(page, "最初の検索");
        await page.waitForTimeout(200);
        await searchMeaning(page, "二回目の検索");

        await expect(page.locator(".pdf-finder-highlight").first()).toBeVisible();
        await page.waitForTimeout(2000);

        // The newer search's result is still the one shown.
        const shown = await page.locator("ol li").count();
        expect(shown).toBe(1);
        await expect(page.locator("ol li").first()).toBeVisible();
    });

    test("replacing the PDF clears the previous document's results", async ({ page }) => {
        await openFixture(page);
        const [target] = await firstSegmentIds(page, 1);

        await page.route("**/api/search", respondWith([target]));
        await searchMeaning(page, "解約について");
        await expect(page.locator("ol li")).toHaveCount(1);

        await page.setInputFiles('input[type="file"]', FIXTURE);
        await page.waitForSelector(".pdf-finder-page");

        await expect(page.locator("ol li")).toHaveCount(0);
        await expect(page.locator(".pdf-finder-highlight")).toHaveCount(0);
    });

    test("an API failure shows a search error, not no match", async ({ page }) => {
        await openFixture(page);

        await page.route("**/api/search", async (route) => {
            await route.fulfill({
                status: 502,
                json: { error: { code: "provider_unavailable", message: "The search could not be completed." } },
            });
        });

        await searchMeaning(page, "解約したらお金は戻りますか");

        await expect(page.getByText("The search could not be completed")).toBeVisible();
        await expect(page.getByText("met the relevance threshold")).toHaveCount(0);
        await expect(page.getByText("No matching text was found")).toHaveCount(0);
    });

    test("shows the model's own judgement on a meaning result and nothing of the kind on an exact one", async ({ page }) => {
        // §3: the numbers are shown because §14.19 found the same passage crossing all three §7
        // bands depending on its request. A reader who cannot see them cannot tell a passage the
        // model was sure of from one that scraped into the list.
        await openFixture(page);
        const [target] = await firstSegmentIds(page, 1);

        await page.route("**/api/search", respondWith([target]));
        await searchMeaning(page, "解約の条件について");
        await expect(page.locator("ol li")).toHaveCount(1);

        const item = page.locator("ol li").first();
        // 0.95 and 0.8 are what the mocked provider returned for this passage.
        await expect(item).toContainText("95%");
        await expect(item).toContainText("confident");
        await expect(item).toContainText("certainty 0.80");
        // Never as a similarity measurement: §3 still forbids "98% match".
        await expect(page.getByText(/\d+% match/u)).toHaveCount(0);
        // The explanatory line is gone (§14.33); the accessible label naming whose judgement it is
        // is what remains, and it is the only place the word survives.
        await expect(page.getByText("Not a measured match")).toHaveCount(0);
        await expect(item.getByLabel(/^Model judgment:/u)).toHaveCount(1);

        // Exact search produces no judgement, so nothing of the kind may appear.
        await searchExact(page, "第");
        await expect(page.locator("ol li").first()).not.toContainText("certainty");
    });

    test("emphasises only the query terms that literally appear in a passage", async ({ page }) => {
        await openFixture(page);

        // Exact search: every result contains the query, so every preview carries the emphasis.
        await searchExact(page, "返還");
        await expect(page.locator("ol li")).not.toHaveCount(0);
        await expect(page.locator("ol li mark").first()).toHaveText("返還");

        // A query too short to be a term emphasises nothing rather than the whole passage.
        await searchExact(page, "第");
        await expect(page.locator("ol li")).not.toHaveCount(0);
        await expect(page.locator("ol li mark")).toHaveCount(0);

        // A query whose words appear nowhere emphasises nothing rather than guessing. Exact search
        // finds no result for it either, so the meaning path supplies the passage.
        const [target] = await firstSegmentIds(page, 1);
        await page.route("**/api/search", respondWith([target]));
        await searchMeaning(page, "ばらの花の育てかた");
        await expect(page.locator("ol li")).toHaveCount(1);
        await expect(page.locator("ol li mark")).toHaveCount(0);
    });

    test("reports what the last meaning search cost, in questions and in requests", async ({ page }) => {
        await openFixture(page);
        const [target] = await firstSegmentIds(page, 1);
        const segmentCount = Number((await page.locator("footer p").textContent())?.match(/(\d+) searchable segments/u)?.[1]);

        await page.route("**/api/search", respondWith([target]));
        await searchMeaning(page, "解約の条件について");

        // One question per segment, in the number of requests the response declared. The two bill
        // separately, so neither can be derived from the other.
        await expect(page.locator("footer p")).toContainText(`${segmentCount} Jev questions in 3 API calls`);
    });

    test("opens the viewer fitted to its pane, and Fit returns to it after zooming", async ({ page }) => {
        await openFixture(page);

        const fitted = (await page.getByLabel("Zoom level").textContent()) ?? "";
        // The pane is wider than a page at 100%, so fitting it is a different number.
        expect(fitted).not.toBe("100%");
        await expect(page.getByRole("button", { name: "Fit" })).toHaveAttribute("aria-pressed", "true");

        await setZoom(page, "100%");
        await expect(page.getByRole("button", { name: "Fit" })).toHaveAttribute("aria-pressed", "false");

        await page.getByRole("button", { name: "Fit" }).click();
        await expect(page.getByLabel("Zoom level")).toHaveText(fitted);
    });

    test("names the page currently in view", async ({ page }) => {
        await openFixture(page);
        await expect(page.getByText(/^1 \/ \d+$/u)).toBeVisible();

        // Scrolling the viewer, not the window: the pages live in their own scroll container.
        await page.locator(".pdf-finder-page").nth(1).scrollIntoViewIfNeeded();
        await expect(page.getByText(/^2 \/ \d+$/u)).toBeVisible();
    });

    test("the divider resizes the results panel", async ({ page }) => {
        await openFixture(page);

        const panel = page.locator("aside");
        const before = (await panel.boundingBox())!.width;

        const divider = page.getByRole("separator", { name: "Resize results panel" });
        const handle = (await divider.boundingBox())!;
        await page.mouse.move(handle.x + handle.width / 2, handle.y + handle.height / 2);
        await page.mouse.down();
        await page.mouse.move(handle.x + handle.width / 2 + 80, handle.y + handle.height / 2, { steps: 8 });
        await page.mouse.up();

        const dragged = (await panel.boundingBox())!.width;
        expect(dragged).toBeGreaterThan(before + 40);

        // A pointer drag is not an accessible control on its own.
        await divider.focus();
        await divider.press("ArrowLeft");
        expect((await panel.boundingBox())!.width).toBeLessThan(dragged);
    });

    test.describe("results belong to the search that produced them", () => {
        test("does not re-describe an old result list with the edited query", async ({ page }) => {
            // Reproduced: after a meaning search, typing a new query re-emphasised the *old*
            // passages against text nobody had searched for, and switching to Exact text relabelled
            // them as exact results.
            await openFixture(page);
            const [target] = await firstSegmentIds(page, 1);
            await page.route("**/api/search", respondWith([target]));

            // A query whose text really appears in the passage, so there is emphasis to lose.
            await searchMeaning(page, "第1条");
            await expect(page.locator("ol li mark")).not.toHaveCount(0);

            // Edit without submitting. The results stay — there is nothing wrong with still seeing
            // what you last searched for — but they are still described by the query that made them.
            await page.getByLabel("Search query").fill("まったく関係のない語");
            await expect(page.locator("ol li")).toHaveCount(1);
            await expect(page.locator("ol li mark")).not.toHaveCount(0);

            // And switching mode does not relabel them either: a meaning result keeps its
            // judgement, which an exact result never has.
            await page.getByRole("radio", { name: "Exact text" }).click();
            await expect(page.locator("ol li")).toHaveCount(1);
            await expect(page.locator("ol li").first()).toContainText("certainty");
        });

        test("keeps the reader's chosen passage when the final ranking arrives", async ({ page }) => {
            // Selection used to be an array index, and the final response reset it to zero — so a
            // reader who picked the second passage while the search was still streaming had their
            // choice undone at the last moment.
            await openFixture(page);
            const ids = await firstSegmentIds(page, 3);
            await page.route("**/api/search", respondWith(ids));

            await searchMeaning(page, "解約の条件について");
            await expect(page.locator("ol li")).toHaveCount(3);

            // Compared on the passage text rather than the whole card: selecting a card reveals
            // its context control, so the card's own text is not the same before and after.
            const preview = (index: number) => page.locator("ol li span.line-clamp-4").nth(index).innerText();
            const secondPassage = await preview(1);

            await page.locator("ol li > button").nth(1).click();
            await expect(page.locator("ol li > button[aria-current='true']")).toContainText(secondPassage.slice(0, 20));

            // Re-running the same search re-ranks the list; the reader has not chosen in the new
            // one, so it opens at the top again.
            await searchMeaning(page, "解約の条件について");
            await expect(page.locator("ol li > button[aria-current='true']")).toContainText((await preview(0)).slice(0, 20));
        });

        test("keeps a passage chosen while the search was still streaming", async ({ page }) => {
            // The case an index cannot survive. The reader picks the second passage mid-search; the
            // final line then re-ranks the list so that passage is no longer second and no longer
            // first. An index would follow the position and quietly highlight someone else.
            await installControlledStream(page, { provisional: [[0, 1, 2]], final: [2, 0, 1] });
            await openFixture(page);

            await searchMeaning(page, "解約の条件について");
            await expect(page.locator("ol li")).toHaveCount(3);

            const preview = (index: number) => page.locator("ol li span.line-clamp-4").nth(index).innerText();
            const chosen = (await preview(1)).slice(0, 20);
            await page.locator("ol li > button").nth(1).click();

            await releaseFinalLine(page);
            await expect(page.getByText("may still change")).toHaveCount(0);

            // Same passage, different position.
            await expect(page.locator("ol li > button[aria-current='true']")).toContainText(chosen);
            expect((await preview(1)).slice(0, 20)).not.toBe(chosen);
        });

        test("keeps a chosen passage while later batches re-rank the list", async ({ page }) => {
            // The defect in the place it actually bites: a long search sends a progress line per
            // batch, each one re-ranking. With an index, the reader's passage drifts under them
            // while they are reading it.
            await installControlledStream(page, {
                provisional: [
                    [0, 1, 2],
                    // The chosen passage moves to *last*, so a selection that followed the
                    // position would land somewhere else entirely rather than coincidentally
                    // staying put.
                    [2, 0, 1],
                ],
                final: [2, 0, 1],
            });
            await openFixture(page);

            await searchMeaning(page, "解約の条件について");
            await expect(page.locator("ol li")).toHaveCount(3);

            const preview = (index: number) => page.locator("ol li span.line-clamp-4").nth(index).innerText();
            const chosen = (await preview(1)).slice(0, 20);
            await page.locator("ol li > button").nth(1).click();

            await releaseNextProgress(page);
            // Pinned first: the re-ranking really happened and moved the chosen passage off its
            // old position. Without this the selection assertion below could pass simply because
            // nothing changed.
            await expect.poll(async () => (await preview(2)).slice(0, 20)).toBe(chosen);
            await expect(page.locator("ol li > button[aria-current='true']")).toContainText(chosen);

            await releaseFinalLine(page);
            await expect(page.locator("ol li > button[aria-current='true']")).toContainText(chosen);
        });

        test("follows the ranking until the reader chooses", async ({ page }) => {
            // The other half of the rule: before the reader has picked anything, the selection is
            // whatever currently ranks first, so the viewer keeps up with the search.
            await installControlledStream(page, { provisional: [[0, 1, 2]], final: [2, 0, 1] });
            await openFixture(page);

            await searchMeaning(page, "解約の条件について");
            await expect(page.locator("ol li")).toHaveCount(3);

            const preview = (index: number) => page.locator("ol li span.line-clamp-4").nth(index).innerText();
            const provisionalTop = (await preview(0)).slice(0, 20);

            await releaseFinalLine(page);
            await expect(page.getByText("may still change")).toHaveCount(0);

            const finalTop = (await preview(0)).slice(0, 20);
            expect(finalTop).not.toBe(provisionalTop);
            await expect(page.locator("ol li > button[aria-current='true']")).toContainText(finalTop);
        });

        test("clears the provisional highlight when the search then fails", async ({ page }) => {
            // The panel said the search could not be completed while the viewer went on
            // highlighting a passage from a stream that never finished.
            await openFixture(page);
            const [target] = await firstSegmentIds(page, 1);

            await page.route("**/api/search", async (route: Route) => {
                const body = JSON.parse(route.request().postData() ?? "{}") as { documentId: string; requestId: string; segments: { id: string }[] };
                const line = (message: unknown) => `${JSON.stringify(message)}\n`;
                await route.fulfill({
                    status: 200,
                    headers: { "Content-Type": "application/x-ndjson" },
                    body:
                        line({
                            type: "progress",
                            documentId: body.documentId,
                            requestId: body.requestId,
                            evaluated: 1,
                            total: body.segments.length,
                            results: [{ segmentId: target, score: 1.2, relevantProbability: 0.5, confidence: 0.4 }],
                        }) +
                        line({
                            type: "error",
                            documentId: body.documentId,
                            requestId: body.requestId,
                            error: { code: "incomplete_evaluation", message: "Some passages were not evaluated." },
                        }),
                });
            });

            await searchMeaning(page, "解約の条件について");

            await expect(page.getByText("The search could not be completed")).toBeVisible();
            await expect(page.locator("ol li")).toHaveCount(0);
            await expect(page.locator(".pdf-finder-highlight")).toHaveCount(0);
        });
    });

    test("puts the extracted-text control at the right of the panel, with an icon", async ({ page }) => {
        await openFixture(page);

        const control = page.locator("aside").getByRole("button", { name: "View extracted text" });
        await expect(control).toBeVisible();
        // An icon, so the control reads as a control rather than as another line of panel text.
        await expect(control.locator("svg")).toHaveCount(1);

        // Right-aligned: its right edge sits near the panel's, not at the left where the text is.
        const panel = (await page.locator("aside").boundingBox())!;
        const button = (await control.boundingBox())!;
        expect(panel.x + panel.width - (button.x + button.width)).toBeLessThan(40);
        expect(button.x - panel.x).toBeGreaterThan(40);
    });

    test("keeps the extracted-text control with the results, not with the viewer", async ({ page }) => {
        await openFixture(page);
        const [target] = await firstSegmentIds(page, 1);
        await page.route("**/api/search", respondWith([target]));
        await searchMeaning(page, "解約の条件について");

        // It belongs with the things said *about* the search — what each passage was judged to be
        // most of all — rather than with the controls for reading the document.
        await expect(page.locator("aside").getByRole("button", { name: "View extracted text" })).toBeVisible();
        await expect(
            page
                .locator("section")
                .first()
                .getByRole("button", { name: /extracted text/u }),
        ).toHaveCount(0);
    });

    test("returns to the document when another PDF is opened", async ({ page }) => {
        // The extracted text on screen belongs to the document being replaced. Leaving it up meant
        // the new document arrived behind a debug view of the old one's extraction.
        await openFixture(page);
        await page.getByRole("button", { name: "View extracted text" }).click();
        await expect(page.getByRole("button", { name: "Hide extracted text" })).toBeVisible();

        await page.setInputFiles('input[type="file"]', FIXTURE);
        await page.waitForSelector(".pdf-finder-page");

        await expect(page.getByRole("button", { name: "View extracted text" })).toBeVisible();
        await expect(page.locator("article header")).toHaveCount(0);
    });

    test("says what meaning search does before the first one, and asks nothing to be dismissed", async ({ page }) => {
        // What is left of §10's disclosure after §14.31: the panel's pre-search line. It is on
        // screen from the moment a document opens until the first search replaces it, and nothing
        // beside the mode selector says it any more.
        await openFixture(page);
        const [target] = await firstSegmentIds(page, 1);
        await page.route("**/api/search", respondWith([target]));

        await expect(page.getByText("sends the extracted text to do it")).toBeVisible();

        // Nothing has to be acknowledged first.
        await page.getByRole("radio", { name: "Meaning" }).click();
        await page.getByLabel("Search query").fill("解約について");
        await page.getByRole("button", { name: "Search", exact: true }).click();
        await expect(page.locator("ol li")).toHaveCount(1);
        await expect(page.getByRole("button", { name: "Continue" })).toHaveCount(0);
    });

    test("orders the extracted text by judgement after a search, and by document before one", async ({ page }) => {
        await openFixture(page);

        // Before a search: document order, which is what this view is for.
        await page.getByRole("button", { name: "View extracted text" }).click();
        const listed = async () => page.locator("article header span.font-semibold").allInnerTexts();
        const before = await listed();
        expect(before.length).toBeGreaterThan(5);
        expect(before).toEqual(before.map((_, index) => `#${index + 1}`));
        await page.getByRole("button", { name: "Back to document" }).click();

        // A search that scores a late passage highest and a middling one second.
        await page.route("**/api/search", async (route: Route) => {
            const body = JSON.parse(route.request().postData() ?? "{}") as { documentId: string; requestId: string; segments: { id: string }[] };
            const score = (index: number, probability: number) => ({
                segmentId: body.segments[index].id,
                score: 1 + probability,
                relevantProbability: probability,
                confidence: 0.8,
            });
            await route.fulfill({
                contentType: "application/x-ndjson",
                body:
                    JSON.stringify({
                        type: "final",
                        documentId: body.documentId,
                        requestId: body.requestId,
                        status: "matched",
                        results: [score(5, 0.9)],
                        // Every segment judged: #6 green, #3 yellow, everything else below.
                        evaluations: body.segments.map((_, index) => score(index, index === 5 ? 0.9 : index === 2 ? 0.5 : 0.05)),
                        evaluatedSegmentCount: body.segments.length,
                        requestCount: 1,
                        model: "jev-1.13.0",
                        elapsedMs: 10,
                    }) + "\n",
            });
        });
        await searchMeaning(page, "解約の条件について");
        await expect(page.locator("ol li")).toHaveCount(1);

        await page.getByRole("button", { name: "View extracted text" }).click();
        const after = await listed();

        // The two that cleared a threshold come first, highest first; the rest keep document order.
        expect(after.slice(0, 2)).toEqual(["#6", "#3"]);
        const rest = after.slice(2).map((label) => Number(label.slice(1)));
        expect(rest).toEqual([...rest].sort((a, b) => a - b));
        // The number is still the document position, so nothing is lost by reordering.
        expect(new Set(after).size).toBe(after.length);
    });

    test("takes the reader from a passage in the extracted text to that passage on the page", async ({ page }) => {
        // Reading a judgement and then having to find the passage by eye was the gap. The segment
        // ID says where it is, but only to someone willing to count.
        await openFixture(page);
        await page.getByRole("button", { name: "View extracted text" }).click();

        // A segment far enough down that no search returned it, so this cannot be a result click.
        const card = page.locator("article").nth(8);
        const segmentId = (await card.locator("header").innerText()).match(/p\d{3}-s\d{3}/u)![0];
        const passage = (await card.locator("p").last().innerText()).slice(0, 16);

        await card.getByRole("button", { name: `Show ${segmentId} in the document` }).click();

        // The view closes, the passage is highlighted, and the viewer is on its page.
        await expect(page.locator("article header")).toHaveCount(0);
        await expect(page.locator(".pdf-finder-highlight").first()).toBeVisible();
        const highlighted = (await page.locator(".pdf-finder-highlight").allInnerTexts()).join("").replace(/\s+/gu, "");
        expect(highlighted).toContain(passage.replace(/\s+/gu, "").slice(0, 10));
        await expect(page.getByText(`${Number(segmentId.slice(1, 4))} / 3`)).toBeVisible();

        // And the result list still says what the search said, not what the debug view opened.
        await expect(page.locator("ol li")).toHaveCount(0);
    });

    test("offers a way out of the extracted text without scrolling back", async ({ page }) => {
        await openFixture(page);
        await page.getByRole("button", { name: "View extracted text" }).click();

        const back = page.getByRole("button", { name: "Back to document" });
        await expect(back).toBeVisible();

        // Still reachable after scrolling down a long extraction: it is pinned, not at the top.
        await page.locator("article").last().scrollIntoViewIfNeeded();
        await expect(back).toBeInViewport();

        await back.click();
        await expect(page.locator("article header")).toHaveCount(0);
        await expect(page.locator(".pdf-finder-page").first()).toBeVisible();
    });
});
